multimyth.ok=Ok
multimyth.cancel=Cancel
multimyth.add=Add
multimyth.remove=Remove
multimyth.reset=Reset
multimyth.delete=Delete
multimyth.enable=Enable
multimyth.disable=Disable

multimyth.release.release=release
multimyth.release.beta=beta
multimyth.release.unstable=unstable
multimyth.release.latest=latest
multimyth.release.old=prior
multimyth.release.unknown=unknown

multimyth.topPanel.newInstance=New Instance
multimyth.topPanel.folders=Folders
multimyth.topPanel.settings=Settings
multimyth.topPanel.update=Update
multimyth.topPanel.help=Help
multimyth.topPanel.steam.notLoggedIn=Not logged in to steam.
multimyth.topPanel.steam.loggedIn=Welcome, {0}

multimyth.sidePanel.launch=Launch
multimyth.sidePanel.edit=Edit Instance
multimyth.sidePanel.viewMods=View Mods
multimyth.sidePanel.screenshots=View Screenshots
multimyth.sidePanel.installFolder=Install Folder
multimyth.sidePanel.configFolder=Config Folder
multimyth.sidePanel.modFolder=Mod Folder
multimyth.sidePanel.shortcut=Create Shortcut
multimyth.sidePanel.clone=Copy Instance

multimyth.bottomPanel.version=Multimyth version {0}
multimyth.bottomPanel.buildinfo.builtby=built by {0} on {1}
multimyth.bottomPanel.buildinfo.develop=DEVELOPMENT VERSION

multimyth.instance.error=<error/corrupt>
multimyth.instance.popup.delete.title=Are you sure?
multimyth.instance.popup.delete.dialog=Are you sure you want to delete {0}?
multimyth.instance.popup.delete.success=Deletion Successful
multimyth.instance.popup.delete.success.dialog=Successfully deleted {0}

multimyth.instance.create.label.window=Name:
multimyth.instance.create.header.version=Version
multimyth.instance.create.header.type=Type
multimyth.instance.create.header.type.release=Releases
multimyth.instance.create.header.type.beta=Betas
multimyth.instance.create.header.type.import=Imports

multimyth.instance.edit.window.misc.header.name=Name
multimyth.instance.edit.window.misc.header.version=Version
multimyth.instance.edit.window.misc.header.changed=Last Changed

multimyth.instance.edit.window.saves.header.difficulty=Difficulty
multimyth.instance.edit.window.saves.header.played=Last Played

multimyth.instance.edit.window=Edit Window for {0}
multimyth.instance.edit.window.version=Version
multimyth.instance.edit.window.mods=Mods
multimyth.instance.edit.window.saves=Saves

multimyth.instance.edit.window.settings=Settings
multimyth.instance.edit.window.settings.java=Java
multimyth.instance.edit.window.settings.java.override=Java Installation
multimyth.instance.edit.window.settings.java.override.java.auto=Auto-Detect
multimyth.instance.edit.window.settings.java.override.java.browse=Browse
multimyth.instance.edit.window.settings.java.override.java.test=Test
multimyth.instance.edit.window.settings.java.override.memory=Memory
multimyth.instance.edit.window.settings.java.override.memory.min=Minimum Memory Allocation:
multimyth.instance.edit.window.settings.java.override.memory.max=Maximum Memory Allocation:
multimyth.instance.edit.window.settings.java.override.args=Java Arguments

multimyth.instance.edit.window.settings.console=Console Settings
multimyth.instance.edit.window.settings.console.show=Show console while the game is running?
multimyth.instance.edit.window.settings.console.close=Automatically close console when the game quits?
multimyth.instance.edit.window.settings.console.crash=Show console when the game crashes?

multimyth.instance.edit.window.logs=Logs
multimyth.instance.edit.window.logs.reload=Reload
multimyth.instance.edit.window.logs.copy=Copy to Clipboard
multimyth.instance.edit.window.logs.upload=Upload
multimyth.instance.edit.window.logs.clean=Clean

multimyth.instance.edit.window.logs.clean.confirm=Are you sure you want to delete all log files?

multimyth.popup.downloading.title=Downloading {0} {1}
multimyth.popup.downloading.text=Download is in progress. This may take a while.
multimyth.popup.download.title.failed=Download failed
multimyth.popup.download.text.failed=Download failed: {0}

multimyth.error.ass=This machine is ass. Session Terminated.
multimyth.error.unexpected=Unexpected Error Occurred: {0}
multimyth.error.delete.fail=Failed to delete {0}
multimyth.error.steam.signedout=You have been signed out of Steam. Until you sign in again, you can only play versions that are already installed.
multimyth.error.steam.signin.fail=Failed to authenticate with Steam: {0}